server {
    listen 80;
    server_name localhost;

    # 1. Tambahkan baris ini agar Nginx mengenali format css, js, dll
    include /etc/nginx/mime.types;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Kunci agar React Router berjalan lancar
        try_files $uri $uri/ /index.html; 
    }

    # 2. Opsional tapi sangat disarankan: 
    # Aturan khusus untuk file statis agar Nginx me-return 404 jika file tidak ditemukan
    # (bukan me-return index.html yang merusak parsing CSS/JS di browser)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        root /usr/share/nginx/html;
        try_files $uri =404;
        expires max;
        access_log off;
    }
}